version: 2
jobs:
  build:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
      POSTGRES_HOST: localhost
      TEST_DB_CONNECTION_STRING: postgresql://postgres:postgres@localhost:5432/app-test
      APP_KEYS: test keys
      NODE_ENV: test

    docker:
      - image: circleci/node:8.11.4
      - image: circleci/postgres:10-alpine-postgis-ram

    working_directory: ~/repo

    steps:
      - run: sudo apt-get install postgresql-client

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: bin/db reset

      # run tests!
      - run: bin/test --runInBand --ci --forceExit
